import fs from 'node:fs/promises';
import path from 'node:path';
export const roles = [
  {slug:'virtual-content-creator',name:'Virtual Content Creator',price:7999,short:'Create a consistent stream of brand-aware content.',outcome:'Turn your brand brief into social posts, campaign creatives and a content calendar your team can review and publish.',tasks:['Social posts and campaign creatives','Captions, scripts and reel concepts','Content calendars and publishing support','Brand-aware iteration and repurposing'],review:'Your team approves brand claims, sensitive topics, rights to supplied media and the final content before publication.',onboard:'Share your brand guide, audience, approved examples and publishing channels. Agree the content cadence and review owner.',faq:['Can it follow our brand voice?','Yes. Supply brand guidance, approved examples and feedback so drafts can be revised against your standards.'],siblings:['virtual-engineer','virtual-operations-manager']},
  {slug:'virtual-engineer',name:'Virtual Engineer',price:14999,short:'Build, maintain and improve your business software.',outcome:'Move website and app tasks from a backlog into reviewed changes, with clear testing notes and technical handoffs.',tasks:['Website and app work','Fixes, maintenance and deployments','Feature implementation','Technical monitoring and handoffs'],review:'A named human approves production releases, access changes, purchases, migrations and changes affecting customer data. Work is checked against agreed acceptance criteria.',onboard:'Share the repository, test environment, priorities and access boundaries. Agree a review and release process before production work.',faq:['Can it deploy changes?','It can prepare and support deployments within the access and release process you approve. Production releases remain subject to your agreed human approval gates.'],siblings:['virtual-content-creator','virtual-team-leader']},
  {slug:'virtual-operations-manager',name:'Virtual Operations Manager',price:9999,short:'Keep tasks, reporting and workflows moving.',outcome:'Keep an operating view of your work: who owns the next step, what is waiting and what needs a decision.',tasks:['Task tracking and follow-ups','Daily and weekly reporting','Workflow coordination','Process checks and escalation'],review:'People retain authority over staffing, payments, business commitments and priority changes. Exceptions and unclear instructions are escalated to the agreed owner.',onboard:'Map your task system, recurring reports, workflow owners and escalation rules. Begin with a bounded operating routine.',faq:['Will it change our processes automatically?','It follows the routines and permissions you agree during setup. Changes to policy or operating scope go to your designated human owner.'],siblings:['virtual-team-leader','virtual-support-agent-chat']},
  {slug:'virtual-team-leader',name:'Virtual Team Leader',price:12999,short:'Coordinate ownership, progress and exceptions.',outcome:'Coordinate your virtual workforce with clear delegation, progress checks and management summaries.',tasks:['Delegation and ownership tracking','Progress monitoring','Escalation and exception handling','Management summaries'],review:'Your human manager sets goals, priorities and decision authority. Personnel decisions, material commitments and unresolved exceptions remain human-reviewed.',onboard:'Define the team, responsibilities, approved workflows and reporting cadence. Set explicit escalation and approval boundaries.',faq:['Does it replace our human manager?','No. It coordinates agreed work and prepares summaries. Your human manager remains responsible for direction, approvals and decisions about people.'],siblings:['virtual-operations-manager','virtual-engineer']},
  {slug:'virtual-sales-agent-chat',name:'Virtual Sales Agent — Chat',price:6999,short:'Qualify enquiries and keep follow-ups organised.',outcome:'Help enquiries progress through approved chat conversations, with useful lead information and a clear handoff to your sales team.',tasks:['WhatsApp and web lead qualification','Follow-ups and nurturing','Product and project information','CRM/LMS updates and human handoff'],review:'A person approves pricing exceptions, contracts and material claims. The virtual employee escalates requests outside approved information or permissions.',onboard:'Supply approved product information, lead stages, consent rules and follow-up guidance. Connect supported channels and your CRM/LMS after access review.',faq:['Can it use our existing WhatsApp and CRM?','Compatibility is checked during the Fit Call. Supported integrations depend on the tools, permissions and channel setup available to your business.'],siblings:['virtual-sales-agent-voice','virtual-support-agent-chat']},
  {slug:'virtual-support-agent-chat',name:'Virtual Support Agent — Chat',price:5999,short:'Answer routine queries and route customer issues.',outcome:'Give customers answers from approved material, record the issue and send exceptions to a person with the right context.',tasks:['Customer queries','Status updates and FAQs','Ticket and issue routing','Human escalation'],review:'Refunds, account changes, sensitive customer requests and disputed answers go to a human. Responses stay within your approved knowledge and access boundaries.',onboard:'Provide support FAQs, approved status sources, ticket categories and escalation contacts. Agree how sensitive or unresolved issues are handled.',faq:['What happens when it cannot answer?','It records the available context and routes the query to your designated human support contact instead of inventing an answer.'],siblings:['virtual-support-agent-voice','virtual-operations-manager']},
  {slug:'virtual-sales-agent-voice',name:'Virtual Sales Agent — Voice',price:9999,usage:true,short:'Qualify leads and arrange appointments by voice.',outcome:'Run approved sales call flows, capture outcomes and pass qualified conversations into your business workflow.',tasks:['Outbound calling and qualification','Follow-up calls','Appointment booking','Call outcomes synced into the business workflow'],review:'Your team approves calling audiences, consent and scripts. Negotiation, contracts, pricing exceptions and sensitive conversations require a human handoff.',onboard:'Agree an approved call flow, contact permissions, telephony setup and booking rules. Test the handoff before enabling the agreed calling workflow.',faq:['Is calling usage included?','No. The role costs ₹9,999/month plus usage. Voice, telephony and third-party communication usage are billed separately.'],siblings:['virtual-sales-agent-chat','virtual-support-agent-voice']},
  {slug:'virtual-support-agent-voice',name:'Virtual Support Agent — Voice',price:7999,usage:true,short:'Handle routine support calls with human escalation.',outcome:'Support approved inbound and outbound call flows, log issues and route the customer to a person when needed.',tasks:['Inbound and outbound support','Verification flows','Issue logging and routing','Escalation'],review:'Sensitive identity or account decisions, refunds, disputed issues and actions outside approved permissions remain with a human. Verification follows only your agreed process.',onboard:'Provide approved support information, verification boundaries, telephony details and escalation contacts. Test normal and exception paths before activation.',faq:['Is telephony usage included?','No. The role costs ₹7,999/month plus usage. Voice, telephony and third-party communication usage are billed separately.'],siblings:['virtual-support-agent-chat','virtual-sales-agent-voice']}
];
const origin='https://workforce.alterlabs.in';
const root=path.resolve('workforce');
const reference=await fs.readFile('scripts/workforce/reference/service.html','utf8');
const css=reference.match(/<link rel="stylesheet"[^>]*href="([^"]+)"/)[1];
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const money=n=>'₹'+n.toLocaleString('en-IN');
const arrow='<svg class="ip-btn__icon" aria-hidden="true" focusable="false"><use href="#ip-i-arrow"/></svg>';
const whatsapp=(label,role='virtual team')=>`<a class="ip-btn ip-btn--primary" data-analytics-event="whatsapp_click" href="https://wa.me/917739108923?text=${encodeURIComponent('Hi AlterLabs, I would like to discuss '+role+' with Alter Workforce.')}" target="_blank" rel="noopener"><span>${esc(label)}</span>${arrow}</a>`;
const contactLink='<a class="ip-btn ip-btn--ghost" data-analytics-event="workforce_fit_call_click" href="https://alterlabs.in/?scene=09">Arrange a Fit Call</a>';
const absolute=s=>s.replaceAll('href="/','href="https://alterlabs.in/');
const sprite=reference.match(/<svg class="ip-sprite"[\s\S]*?<\/svg>/)[0];
let header=absolute(reference.match(/<header class="site-nav">[\s\S]*?<\/header>/)[0]).replace(' aria-current="page"','');
header=header.replace('href="https://alterlabs.in/products/">Products','href="/#roles">Virtual employees').replace('class="nav-cta" href="https://alterlabs.in/?scene=09"','class="nav-cta" href="#contact"');
const footer=absolute(reference.match(/<footer class="ip-footer">[\s\S]*?<\/footer>/)[0]).replace('<a href="https://alterlabs.in/products/">Products</a>','<a href="/">Alter Workforce</a>\n<a href="https://alterlabs.in/products/">Products</a>');
const actionbar=reference.match(/<div class="action-bar">[\s\S]*?<\/div>/)[0];
const disclosure='Alter Workforce roles are software-based virtual employees operated through AlterLabs systems and integrations. They are not human employees. Your business retains human oversight and decision authority.';
const usage='Voice, telephony and third-party communication usage are billed separately. Connected services and permitted actions are agreed during setup.';
const commonFaq=[
 ['Are these human employees?',disclosure],
 ['What stays under human control?','You set the scope, access permissions and approval rules. High-impact decisions, sensitive actions and exceptions go to your designated human owner.'],
 ['What does business setup cost?','Business Setup costs ₹9,999 one-time. Setup covers the agreed roles, workflow mapping, access boundaries, supported integrations and review process.'],
 ['Is communication usage included?',usage],
 ['Can they work around the clock?','Configured software routines can run 24×7. Operation depends on connected tools, approved workflows and service availability; this is not a promise of uninterrupted service or immediate human support.'],
 ['How do I start?','Start with a Fit Call or message AlterLabs on WhatsApp. We review your workflow, confirm compatible tools and agree the scope and responsibilities before setup.']
];
function faqs(items){return `<section class="ip-section" id="faq"><div class="ip-wrap ip-split"><h2 class="ip-h2">Questions, answered</h2><div class="ip-faq">${items.map(([q,a])=>`<details class="ip-faq__item"><summary class="ip-faq__q"><span>${esc(q)}</span><i class="ip-faq__icon" aria-hidden="true"></i></summary><div class="ip-faq__a"><p>${esc(a)}</p></div></details>`).join('')}</div></div></section>`;}
function section(title,body,id=''){return `<section class="ip-section"${id?` id="${id}"`:''}><div class="ip-wrap ip-split"><h2 class="ip-h2">${esc(title)}</h2><div class="ip-prose">${body}</div></div></section>`;}
function hero(title,lede,crumb=''){return `<section class="ip-hero"><div class="ip-hero__sky" aria-hidden="true"></div><div class="ip-wrap ip-hero__inner"><nav class="ip-crumb" aria-label="Breadcrumb"><ol><li><a href="https://alterlabs.in/">AlterLabs</a></li><li>${crumb?'<a href="/">Alter Workforce</a>':'<span aria-current="page">Alter Workforce</span>'}</li>${crumb?`<li><span aria-current="page">${esc(crumb)}</span></li>`:''}</ol></nav><div class="ip-hero__content"><p class="ip-eyebrow">ALTER WORKFORCE</p><h1 class="ip-hero__title" id="ip-title">${title}</h1><p class="ip-hero__lede">${esc(lede)}</p><div class="ip-actions">${whatsapp(crumb?'Start with this role':'Build my virtual team',crumb||'virtual team')}<a class="ip-btn ip-btn--ghost" data-analytics-event="workforce_role_compare" href="/#roles">Start with one role</a></div><p class="wf-disclosure">Software-based virtual employees, with human oversight.</p></div></div><div class="ip-horizon" aria-hidden="true"><div class="ip-horizon__planet"></div><div class="ip-horizon__apex"></div><div class="ip-horizon__star"></div></div></section>`;}
function card(r){return `<li class="ip-card ip-card--product"><span class="ip-card__icon ip-card__icon--product" aria-hidden="true"><svg viewBox="0 0 24 24"><use href="#ip-i-${r.usage?'mic':'flow'}"/></svg></span><h3 class="ip-card__title"><a class="ip-card__link" href="/${r.slug}/" data-analytics-event="workforce_role_click">${esc(r.name)}</a></h3><p class="ip-card__description">${esc(r.short)}</p><p class="wf-price">${money(r.price)}<span>/month${r.usage?' + usage':''}</span></p><span class="ip-card__go"><span class="ip-card__arrow" aria-hidden="true">${arrow}</span><span class="ip-card__go-label">Explore ${esc(r.name.replace('Virtual ',''))}</span></span></li>`;}
function onboarding(r){return section('Onboarding',`<p>${esc(r.onboard)}</p><p>Business Setup: <strong>₹9,999 one-time</strong>. Confirm the scope, supported integrations, approval owner and communication usage before activation.</p>`);}
const cta=`<section class="ip-contact" id="contact"><div class="ip-wrap ip-contact__inner"><div class="ip-contact__copy"><p class="ip-eyebrow">Your next step</p><h2 class="ip-contact__title"><span>Build my</span><span class="ip-grad">virtual team</span></h2><p class="ip-contact__lede">Tell us which work needs a reliable next step. Start with one role or plan a connected team.</p></div><div class="ip-panel"><div class="ip-panel__head"><p class="ip-panel__title">Talk to AlterLabs</p><p class="ip-panel__note">Agree the workflow, permissions and scope.</p></div><div class="ip-actions">${whatsapp('Build my virtual team')}${contactLink}</div><a class="ip-action" href="mailto:sales@alterlabs.in" data-analytics-event="email_click"><span class="ip-action__text"><span class="ip-action__label">Email</span><span class="ip-action__value">sales@alterlabs.in</span></span></a></div></div></section>`;
function offer(name,price,url,description,monthly=true){return {'@type':'Offer',name,price:String(price),priceCurrency:'INR',url,description,priceSpecification:monthly?{'@type':'UnitPriceSpecification',price:String(price),priceCurrency:'INR',billingDuration:'P1M'}:{'@type':'PriceSpecification',price:String(price),priceCurrency:'INR'},itemOffered:{'@type':'Service',name,provider:{'@id':'https://alterlabs.in/#organization'}}};}
function document(title,description,route,body,faq,role){
 const url=origin+route;
 const graph=[{'@type':'Organization','@id':'https://alterlabs.in/#organization',name:'AlterLabs',url:'https://alterlabs.in/'},{'@type':'WebSite','@id':origin+'/#website',name:'Alter Workforce',url:origin+'/',inLanguage:'en-IN',publisher:{'@id':'https://alterlabs.in/#organization'}},{'@type':'FAQPage','@id':url+'#faq',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}];
 if(role){graph.push({'@type':'Service','@id':url+'#service',name:role.name,url,description:role.outcome,provider:{'@id':'https://alterlabs.in/#organization'},offers:offer(role.name,role.price,url,role.usage?'Monthly role fee; communication usage billed separately.':'Monthly role fee; Business Setup ₹9,999 one-time.')},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Alter Workforce',item:origin+'/'},{'@type':'ListItem',position:2,name:role.name,item:url}]});}
 else graph.push({'@type':'OfferCatalog','@id':url+'#roles',name:'Alter Workforce roles and bundles',itemListElement:[...roles.map(r=>offer(r.name,r.price,origin+'/'+r.slug+'/',r.usage?'Monthly fee plus separately billed communication usage.':'Monthly role fee.')),offer('Any 3 Virtual Employees',24999,url+'#bundles',usage),offer('Complete Virtual Team',49999,url+'#bundles',usage),offer('Business Setup',9999,url+'#setup','One-time setup fee.',false)]});
 return `<!doctype html>\n<html lang="en-IN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#010409"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:site_name" content="Alter Workforce by AlterLabs"><meta property="og:locale" content="en_IN"><meta property="og:image" content="https://alterlabs.in/og.jpg"><meta property="og:image:alt" content="AlterLabs — Build a Brighter Reality"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="https://alterlabs.in/og.jpg"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="stylesheet" href="${css}"><link rel="stylesheet" href="/assets/workforce.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script><script src="/analytics-events.js" defer></script></head><body class="ip"><a class="skip-link" href="#main">Skip to content</a>${sprite}${header}<main id="main" tabindex="-1">${body}${faqs(faq)}${cta}${section('Software-based virtual employees',`<p>${esc(disclosure)}</p><p>${esc(usage)}</p>`)}</main>${footer}${actionbar}</body></html>\n`;
}
const homeBody=hero('<span>Hire your next</span> <span class="ip-grad">employee.</span>','Virtual employees that work inside your business — creating, building, selling, supporting and coordinating every day.')+
 `<section class="ip-section"><div class="ip-wrap"><h2 class="ip-h2">Built around your business</h2><ul class="ip-grid">${[['24×7 routines','Configured software routines can run around the clock, subject to service availability.'],['Role-based work','Start with clear responsibilities and a named approval owner.'],['Connected workflows','Use supported business tools and integrations agreed during setup.'],['Private business environment','Work within permissioned tools and access boundaries set for your business.']].map(([h,p])=>`<li class="ip-tile"><div><h3 class="ip-tile__text">${h}</h3><p class="wf-disclosure">${p}</p></div></li>`).join('')}</ul></div></section>`+
 `<section class="ip-section" id="roles"><div class="ip-wrap"><h2 class="ip-h2">Choose your virtual employees</h2><p class="ip-prose">Start with the work your business needs every day.</p><ul class="ip-cards" role="list">${roles.map(card).join('')}</ul><p class="ip-pricing-note">Monthly prices in INR. Voice roles add usage. Business Setup: ₹9,999 one-time. ${usage}</p></div></section>`+
 `<section class="ip-section" id="bundles"><div class="ip-wrap"><h2 class="ip-h2">Build a virtual workforce</h2><div class="ip-pricing-wrap"><ul class="ip-pricing" role="list"><li class="ip-plan"><h3 class="ip-plan__name">Any 3 Virtual Employees</h3><p class="ip-plan__price">₹24,999</p><p class="ip-plan__unit">/month</p><p class="ip-prose">Choose any three launch roles for your business workflow. Voice and third-party communication usage are billed separately.</p><div class="ip-actions">${whatsapp('Build my 3-role team','a 3-role virtual team')}</div></li><li class="ip-plan"><h3 class="ip-plan__name">Complete Virtual Team</h3><p class="ip-plan__price">₹49,999</p><p class="ip-plan__unit">/month + communication usage</p><p class="ip-prose">Bring the launch roles together across content, engineering, operations, leadership, sales and support.</p><div class="ip-actions">${whatsapp('Build my complete team','the complete virtual team')}</div></li></ul><p class="ip-pricing-note">Business Setup is ₹9,999 one-time. ${usage}</p></div></div></section>`+
 section('How it works','<ol class="wf-steps"><li><strong>Map the work.</strong> Tell us the tasks, tools and outcomes you need.</li><li><strong>Choose the roles.</strong> Start with one virtual employee or a connected team.</li><li><strong>Set the boundaries.</strong> Agree access, approved information, human review and escalation.</li><li><strong>Connect and operate.</strong> Test the agreed workflow, review results and refine it with your team.</li></ol>')+
 section('Business Setup — ₹9,999 one-time','<p>Map responsibilities, connect supported tools and establish the review process for your virtual workforce.</p><p>Your business chooses what each role can access, which actions need approval and who receives exceptions. Confirm integrations, scope and communication usage before work starts.</p>','setup');
await fs.writeFile(path.join(root,'index.html'),document('Alter Workforce | Hire Virtual Employees for Your Business','Hire software-based virtual employees for content, engineering, operations, sales and support. Explore eight roles from ₹5,999/month with human oversight.','/',homeBody,commonFaq));
for(const r of roles){const route='/'+r.slug+'/'; const faq=[r.faq,...commonFaq.slice(0,4)]; const body=hero(`<span>${esc(r.name.split(' — ')[0])}</span>${r.usage||r.name.includes(' — ')?` <span class="ip-grad">${esc(r.name.split(' — ')[1])}</span>`:''}`,r.outcome,r.name)+
 section('Responsibilities and what it can do',`<ul class="wf-steps">${r.tasks.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`)+section('What stays human-reviewed',`<p>${esc(r.review)}</p><p>Escalation and approvals are defined with your business during setup.</p>`)+onboarding(r)+
 section('Pricing',`<p class="wf-price">${money(r.price)}<span>/month${r.usage?' + usage':''}</span></p><p>Business Setup: ₹9,999 one-time. ${esc(usage)}</p><div class="ip-actions">${whatsapp('Start with this role',r.name)}${contactLink}</div>`,'pricing')+
 section('Work better together',`<ul class="ip-links"><li><a href="/">Explore the full Alter Workforce</a></li>${r.siblings.map(s=>{const sibling=roles.find(r=>r.slug===s);return `<li><a href="/${s}/">${esc(sibling.name)}</a></li>`;}).join('')}<li><a href="/#bundles">Compare virtual team bundles</a></li></ul>`);
 await fs.mkdir(path.join(root,r.slug),{recursive:true}); await fs.writeFile(path.join(root,r.slug,'index.html'),document(`${r.name} | ${money(r.price)}/month | Alter Workforce`,`${r.short} ${money(r.price)}/month${r.usage?' plus usage':''}. Software-based virtual employee with agreed access, human review and ₹9,999 one-time setup.`,route,body,faq,r));}
const lastmod=new Date().toISOString().slice(0,10);
await fs.writeFile(path.join(root,'robots.txt'),`User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`);
await fs.writeFile(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${['/',...roles.map(r=>'/'+r.slug+'/')].map(p=>`  <url><loc>${origin}${p}</loc><lastmod>${lastmod}</lastmod></url>`).join('\n')}\n</urlset>\n`);
await fs.writeFile(path.join(root,'404.html'),document('Page not found | Alter Workforce','Explore Alter Workforce virtual employees.','/',section('Page not found','<p>This address is unavailable. <a href="/">Explore Alter Workforce</a>.</p>'),[],null).replace('<title>','<meta name="robots" content="noindex"><title>'));
console.log('Built workforce homepage, 8 role pages, robots and sitemap.');
